[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
walien_pool = "Hp8rd1zGZdyJNidxx4461e9buwGhab9DcGnsc23wha3"

[programs.devnet]
walien_pool = "Hp8rd1zGZdyJNidxx4461e9buwGhab9DcGnsc23wha3"

[programs.mainnet]
walien_pool = "Hp8rd1zGZdyJNidxx4461e9buwGhab9DcGnsc23wha3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[path]
idl_path = "./target/idl/walien_pool.json"
binary_path = "./target/deploy/walien_pool.so"
